CREATE TABLE `dn_fossil` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uid` int(11) unsigned NOT NULL DEFAULT '0',
  `comment_id` int(11) unsigned NOT NULL DEFAULT '0',
  `classification_id` int(10) unsigned NOT NULL DEFAULT '0',
  `classification_id_arr` varchar(255) NOT NULL DEFAULT '',
  `district_id` varchar(20) NOT NULL DEFAULT '',
  `district_id_arr` varchar(255) NOT NULL DEFAULT '',
  `geo_age_id` int(10) unsigned NOT NULL DEFAULT '0',
  `geo_age_id_arr` varchar(255) NOT NULL DEFAULT '',
  `serial_no` varchar(25) NOT NULL DEFAULT '',
  `name_zh` varchar(100) NOT NULL DEFAULT '',
  `name_en` varchar(100) NOT NULL DEFAULT '',
  `owner` varchar(50) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `geo_layer` varchar(255) NOT NULL DEFAULT '',
  `longitude` varchar(10) NOT NULL DEFAULT '',
  `latitude` varchar(10) NOT NULL DEFAULT '',
  `altitude` varchar(10) NOT NULL DEFAULT '',
  `abstract` varchar(255) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `photo` text NOT NULL,
  `restore_photo` text NOT NULL,
  `storage_name` varchar(100) NOT NULL DEFAULT '',
  `storage_no` varchar(100) NOT NULL DEFAULT '',
  `num` int(10) unsigned NOT NULL DEFAULT '0',
  `material` text NOT NULL,
  `is_public` tinyint(2) unsigned NOT NULL DEFAULT '1',
  `status` tinyint(2) unsigned NOT NULL DEFAULT '1',
  `get_time` int(10) unsigned NOT NULL DEFAULT '0',
  `dtime` int(10) NOT NULL DEFAULT '0',
  `ctime` int(10) NOT NULL DEFAULT '0',
  `utime` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `serial_no` (`serial_no`),
  KEY `uid` (`uid`),
  KEY `comment_id` (`comment_id`),
  KEY `classfication_id` (`classification_id`),
  KEY `district_id` (`district_id`),
  KEY `geo_age_id` (`geo_age_id`),
  KEY `name_zh` (`name_zh`,`name_en`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

